/*
 * Copyright (c) 2018 Aspose Pty Ltd. All Rights Reserved.
 *
 * Licensed under the MIT (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       https://github.com/aspose-omr-cloud/aspose-omr-cloud-dotnet/blob/master/LICENSE
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace Aspose.OMR.Client.Utility
{
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// Preprocessing preset
    /// </summary>
    public enum PreprocessingPreset
    {
        [Description("Templates that were generated by Aspose using Template Generation dialog.")]
        [Display(Name="Aspose Generated")]
        AsposeImages,

        [Description("Low-noise photos or scans with easily distinguishable bubbles and considerable gap between them.")]
        [Display(Name = "Good Quality")]
        GoodQuiality,

        [Description("Certain requirements are not met (e.g. high-noise photos, low contrast bubbles, small gaps between bubbles, but not simultaneously).")]
        [Display(Name = "Normal Quality")]
        NormalQuality,

        [Description("Custom Settings allows you to manually modify preprocessing configuration.")]
        [Display(Name = "Custom Settings")]
        CustomSettings
    }
}
