/*
 * Copyright (c) 2018 Aspose Pty Ltd. All Rights Reserved.
 *
 * Licensed under the MIT (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://github.com/aspose-omr-cloud/aspose-omr-cloud-dotnet/blob/master/LICENSE
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/*
 * Aspose.OMR for Cloud API Reference
 * Aspose.OMR for Cloud helps performing optical mark recognition in the cloud
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


using System;

namespace Com.Aspose.Omr.Client {
  /// <summary>
  /// API Exception
  /// </summary>
  public class ApiException : Exception {
      /// <summary>
      /// Gets or sets the error code (HTTP status code)
      /// </summary>
      /// <value>The error code (HTTP status code).</value>
      public int ErrorCode { get; set; }

      /// <summary>
      /// Gets or sets the error content (body json object)
      /// </summary>
      /// <value>The error content (Http response body).</value>
      public Object ErrorContent { get; private set; }

      /// <summary>
      /// Initializes a new instance of the <see cref="ApiException"/> class.
      /// </summary>
      public ApiException() {}

      /// <summary>
      /// Initializes a new instance of the <see cref="ApiException"/> class.
      /// </summary>
      /// <param name="errorCode">HTTP status code.</param>
      /// <param name="message">Error message.</param>
      public ApiException(int errorCode, string message) : base(message) {
          this.ErrorCode = errorCode;
      }

      /// <summary>
      /// Initializes a new instance of the <see cref="ApiException"/> class.
      /// </summary>
      /// <param name="errorCode">HTTP status code.</param>
      /// <param name="message">Error message.</param>
      /// <param name="errorContent">Error content.</param>
      public ApiException(int errorCode, string message, Object errorContent = null) : base(message) {
          this.ErrorCode = errorCode;
          this.ErrorContent = errorContent;
      }

  }

}
